/lyrics Endpoint
Dhravya/dhravyaAPI pull request #33
Opened 2022-01-08 11:36 UTC by PolyAnthi

Added:
**/lyrics endpoint (uses SRA and LyricsOVH)**
**SQLite Database for caching**

Removed:
**Unwanted Import**

To be removed when merged:
**/coin_value endpoint**

2022-01-08 12:02 UTC, itsnotrin commented
Believe we need to have those qr_code files for the qr code endpoint to work.

2022-01-08 12:03 UTC, itsnotrin commented
Also would prefer if we could use an async sqlite3 library, would work better for us in the long term with multiple requests

2022-01-08 12:04 UTC, itsnotrin commented
Line 424 on app.py , can you explain why you removed the check for missing lyrics? That'll just cause app errors, no?

2022-01-08 12:04 UTC, itsnotrin commented
Denied until these things are fixed

2022-01-08 12:08 UTC, itsnotrin requested changes
Listed the changes I'd like done in the conversation.

2022-01-09 14:40 UTC, PolyAnthi reviewed
Fixed all stuff Ryan requested and added two new endpoints (truth or dare and Never Have I Ever)

2022-01-09 17:01 UTC, Dhravya requested changes
Here are all my reviews, overall great work lol

2022-01-09 17:01 UTC, Dhravya commented on app.py
> +async def topic(simple: Optional[str] = "False"):
Never have i ever endpoint is named Topic?

2022-01-09 17:01 UTC, Dhravya commented on app.py
> +        return JSONResponse(
Any reason to use JSONresponse?

2022-01-09 17:01 UTC, Dhravya commented on app.py
> +async def truthordare(type: str, simple: Optional[str] = "False"):
Better to make a /truth and /dare imo

2022-01-09 17:01 UTC, Dhravya commented on data/txt/truth.txt
> +What's your really weird secret collection?
More truth questions needed

2022-01-09 17:08 UTC, PolyAnthi commented on app.py
> +async def topic(simple: Optional[str] = "False"):
mb LMAO

2022-01-09 17:08 UTC, PolyAnthi commented on app.py
> +        return JSONResponse(
to return 404

2022-01-09 17:08 UTC, PolyAnthi commented on app.py
> +async def truthordare(type: str, simple: Optional[str] = "False"):
keep in 1 endpoint

2022-01-09 17:09 UTC, PolyAnthi commented on data/txt/truth.txt
> +What's your really weird secret collection?
i think 100 for now is good

2022-01-09 17:09 UTC, Dhravya commented on app.py
> +async def truthordare(type: str, simple: Optional[str] = "False"):
@itsnotrin Thoughts?

2022-01-09 17:11 UTC, PolyAnthi commented on app.py
> +async def topic(simple: Optional[str] = "False"):
fixed

2022-01-09 17:13 UTC, PolyAnthi commented
Can we get this merged soon so when we have new code we have a fresh PR?

2022-01-09 17:15 UTC, Dhravya commented on app.py
> +async def truthordare(type: str, simple: Optional[str] = "False"):
wait for rin to respond smh

2022-01-09 17:15 UTC, Dhravya approved these changes
everything looks good to me

2022-01-09 17:16 UTC, itsnotrin commented
I'll review after my dinner, won't take me long

2022-01-09 17:16 UTC, PolyAnthi commented
> I'll review after my dinner, won't take me long

No problem

2022-01-09 18:01 UTC, itsnotrin commented on app.py
> +async def truthordare(type: str, simple: Optional[str] = "False"):
Have 1 for both endpoints and 1 for each, so 3 total

2022-01-09 18:02 UTC, itsnotrin submitted a review, later dismissed
Do what I suggested on wyr please

2022-01-10 08:09 UTC, PolyAnthi commented
You mean T or D?

On Sun, 9 Jan 2022, 18:02 itsnotrin, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Do what I suggested on wyr please
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Dhravya/dhravyaAPI/pull/33#pullrequestreview-847288243>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AS7GXS2RE3YJMV74XXGI3QLUVHEVBANCNFSM5LQQWJDQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-01-10 08:37 UTC, itsnotrin commented
I mean make an endpoint for either one and then an endpoint for both
so

/truth
/dare
/truthordare

2022-01-10 08:41 UTC, PolyAnthi commented
Ah okay. So truthordare sends both, truth sends a truth and dare sends a
dare


On Mon, 10 Jan 2022, 08:37 itsnotrin, ***@***.***> wrote:

> I mean make an endpoint for either one and then an endpoint for both
> so
>
> /truth
> /dare
> /truthordare
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Dhravya/dhravyaAPI/pull/33#issuecomment-1008646519>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AS7GXS7JKQARQPW6AOTPCDDUVKLGDANCNFSM5LQQWJDQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-01-10 20:37 UTC, itsnotrin commented
Yes

2022-01-11 13:39 UTC, PolyAnthi commented
Aight can do that tonight

On Mon, 10 Jan 2022, 20:37 itsnotrin, ***@***.***> wrote:

> Yes
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Dhravya/dhravyaAPI/pull/33#issuecomment-1009321831>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AS7GXSZM4PRGVLRG64J6HTTUVM7RRANCNFSM5LQQWJDQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-01-11 16:01 UTC, Dhravya commented
Damn this one has been in review since a long time

2022-01-11 19:06 UTC, itsnotrin commented
Happy, merging.

2022-01-11 19:07 UTC, merged

2022-01-13 06:27 UTC, Dhravya reviewed
looks good